# Generated by Django 4.1.2 on 2022-11-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=50, null=True, verbose_name='status_name')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, choices=[('task', 'Задача'), ('bug', 'Ошибка'), ('Enchancement', 'Улучшение')], default='task', max_length=50, null=True, verbose_name='type_name')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='short_description')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('date_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Date_of_Create')),
                ('date_of_update', models.DateTimeField(auto_now=True, verbose_name='Date_of_Update')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.status', verbose_name='Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.type', verbose_name='Type')),
            ],
        ),
    ]
