# Generated by Django 4.1.2 on 2022-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status_name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='type_name'),
        ),
    ]
