# Generated by Django 4.1.2 on 2022-11-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_status_status_name_alter_type_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='type',
        ),
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.ManyToManyField(related_name='type', to='webapp.type', verbose_name='Type'),
        ),
    ]
