# Generated by Django 4.1.2 on 2022-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_todo_type_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.CharField(max_length=50, verbose_name='short_description'),
        ),
    ]
