# Generated by Django 4.1.2 on 2022-11-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_todo_description_alter_todo_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='short_description',
            field=models.CharField(max_length=20, verbose_name='short_description'),
        ),
    ]
