# Generated by Django 4.1.2 on 2022-12-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_todo_description_alter_todo_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField(verbose_name='s_date')),
                ('e_date', models.DateField(blank=True, null=True, verbose_name='e_date')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('desc', models.TextField(max_length=300, verbose_name='desc')),
            ],
        ),
    ]
