# Generated by Django 4.1.2 on 2022-12-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_todo_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='p_id',
        ),
    ]
