# Generated by Django 4.1.2 on 2022-12-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_todo_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='p_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='p_id', to='webapp.projects', verbose_name='p_id'),
            preserve_default=False,
        ),
    ]
